name: Perspective Image
favicon: null
layout_spectrum: 0.2423008440528065
typography_spectrum: 0.6698226651642472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8322542319074273
  lightness: 0.5593403924722224
  saturation: 0.8798372556921095
  rhythmicContrast: 0.6156383373308927
purpose: []
