name: Perspective Image
favicon: null
layout_spectrum: 0.90166
typography_spectrum: 0.90166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#917c5d'
    - '#554233'
    - '#ced3d9'
    - '#439b80'
  brandStrength: 0.5
  lightness: 0.5593403924722224
  saturation: 0.5
  rhythmicContrast: 0.6156383373308927
purpose: []
